# Generated by Django 5.0.3 on 2024-03-07 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp_3', '0002_alter_talaba_options_muallif_tugilgan_sana_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kitob',
            options={'verbose_name': 'Kitob', 'verbose_name_plural': 'Kitoblar'},
        ),
        migrations.AlterModelOptions(
            name='kutubxonachi',
            options={'verbose_name': 'Kutubxonachi', 'verbose_name_plural': 'Kutubxonachilar'},
        ),
        migrations.AlterModelOptions(
            name='muallif',
            options={'verbose_name': 'Muallif', 'verbose_name_plural': 'Mualliflar'},
        ),
        migrations.AlterModelOptions(
            name='record',
            options={'verbose_name': 'Record', 'verbose_name_plural': 'Recordlar'},
        ),
        migrations.AlterUniqueTogether(
            name='talaba',
            unique_together={('ism', 'kurs')},
        ),
    ]
