# Generated by Django 5.0.3 on 2024-03-07 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp_3', '0003_alter_kitob_options_alter_kutubxonachi_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitob',
            name='janr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='kitob',
            name='sahifa',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='muallif',
            name='kitoblar_soni',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
