# Generated by Django 5.0.3 on 2024-03-14 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp_3', '0004_alter_kitob_janr_alter_kitob_sahifa_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='talaba',
            old_name='kitob_soni',
            new_name='k_soni',
        ),
    ]
